---
- hosts: localhost
  connection: local
  gather_facts: False  
  vars_files:
     - aws_auth.yml 
     -  inventory/division1.yml
    
  roles:
    - create-vpc
    - create-keypair
    - create-ec2
   