vpc_name: division1_vpc
vpc_cidr: 10.10.0.0/16
vpc_internet_gateway: "present"
vpc_subnets: 
  - name: db_subnet
    cidr: 10.10.1.0/24
    route_to_internet_gateway: False
    assign_pub_ip_to_instance: False
  - name: app_subnet
    cidr: 10.10.2.0/24
    route_to_internet_gateway: True
    assign_pub_ip_to_instance: True

vpc_security_groups:
  - name: sg1
    description: sg description
    rules:         
      - proto: tcp
        ports:
          - 22
          - 80
          - 443
          - 8080-8082
        cidr_ip: 0.0.0.0/0        
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: 64:ff9b::/96
      - proto: tcp
        ports: 22
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
 
key_pairs:      
  - key_pair_name: k1
    public_key_filename: /home/bhujay/.ssh/id_rsa.pub

list_of_computes:
  - name: c1
    instance_type: t2.micro
    image_id: ami-1c200c73
    key_name: k1
    security_groups: 
      - sg1
    monitoring: no
    tenancy: default
    assign_public_ip: yes
    instance_tags:        
        app: app1
    count: 1
    vpc_subnet_name: app_subnet
    region: "ap-south-1"
    state: present
    
    
    
    
    
  
    
